version: '3'
services:
  redis:
    image: redis:6
    ports:
      - "6379:6379"
  web:
    build:
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
  worker:
    build:
    command: celery -A app.worker.celery_app worker --loglevel=info
    depends_on:
      - redis
